# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29bd351c0c13709f3765e5e23d60c92ccac347cb0a0ad700c044e0ae2a1c5d946ffab3df2b07d98cfb9c0452a6515b7799baab58a01276eef104542a6179d28b

test:
  secret_key_base: bd9f7e977a53a563f684c681f77a59c03e40a0df8a068a7cb5d56f1bf1ad5c3304f2b79ecb86e95d437116aea44eaf6474d7a4bb7a83b2935240a62e516d8e75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
